FROM postgres:13.3

ENV TZ Asia/Tokyo
ENV POSTGRES_DATABASE postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD password
ENV POSTGRES_ROOT_PASSWORD root

COPY docker/infra/postgres/initdb /docker-entrypoint-initdb.d

EXPOSE 5432
